# Generated by Django 2.0 on 2020-09-24 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catatan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gambar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(blank=True, default='', upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='catatan',
            name='gambar',
        ),
        migrations.AddField(
            model_name='gambar',
            name='catatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan', to='catatan.Catatan'),
        ),
    ]
