# Generated by Django 3.1.1 on 2020-09-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catatan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catatan',
            name='ket',
            field=models.TextField(help_text='maksimal 500 karakter', max_length=500),
        ),
    ]
