# Generated by Django 2.2.9 on 2020-10-14 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkl',
            name='tanggal_selesai',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
