# Generated by Django 2.2.9 on 2020-10-15 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0003_auto_20201015_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkl',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mahasiswa', to=settings.AUTH_USER_MODEL),
        ),
    ]
