# Generated by Django 2.2.9 on 2020-10-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0004_auto_20201015_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkl',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
